### PR TITLE
fix: There was a bug in derive/tests/simple.rs

### PR DESCRIPTION
**Pull request by ckaran**
fix: derive/tests/simple.rs failed to compile because of 'Field' ambiguity.

`derive/tests/simple.rs` uses a pair of glob imports, both of which define 'Field'.  This ambiguity was caught by the compiler, and caused a compilation failure when running all tests in the workspace from the root.  This commit fixes the bug.

### CODE REVIEW

**Comment by ckaran** [comment]
I have no idea why, but the failure is in the formatting of the code.  This works on both stable and nightly channels for me.  All other tests are passing, so... ???

**Comment by RustyYato** [comment]
Thanks for the PR, I'll look into this this week.  It's been so long since I looked at this crate, so I'm going to need a minute to get my bearings. The fornat check is probably because I misconfigured it. I'll see wyat I can do about that. I'll probably strip away the other targets besides linux as well, since I'm not doing anything platform specific here.

**Comment by RustyYato** [comment]
@ckaran Would it be possible to split out the last two style formats into a separate PR?

**Comment by ckaran** [comment]
@RustyYato 

>Would it be possible to split out the last two style formats into a separate PR?

As soon as I can figure out how to! :sweat_smile: 

Give me a few moments, working on it now.

**Comment by ckaran** [comment]
@RustyYato OK, just made PRs #26 and #27.  If you apply them in the order #26, #27, #25, then they should apply cleanly.

**Comment by RustyYato** [comment]
Can you fix that one merge conflict, then this will be good to go

**Comment by ckaran** [comment]
OK, just fixed the merge conflict, try it now.

**Comment by RustyYato** [comment]
Looks good

**Pull request merged**
