### PR TITLE
review fmt - oliver

### PR DESCRIPTION
**Pull request by kw-fn**
are this projects issues still active?

### CODE REVIEW

**Comment by ckaran** [comment]
@kw-fn Yes, the project is still active.  By the way, did you do `cargo fmt` using the project's `.rustfmt.toml`?  It looks like there are a bunch of failures in your PR due to that.

**Comment by kw-fn** [comment]
oof yeah that was surprising! no I was looking through the code on a file by file basis
in core and derive, why is so much custom formatting necessary?

other than that I was looking at taking on the `derive` refactor

**Comment by kw-fn** [comment]
closing PR due to errors

**Comment by ckaran** [comment]
The project is still active, but I'm the bottleneck for it, unfortunately... I'm slammed trying to get my PhD. done, and keep seeing this on my list of stuff to get done, and feeling guilty about it.

That said, @RustyYato is the *real* developer on this, having created the project, and pushing it forwards.  I'm just trying to pull together enough time to write some example code up, and maybe, just maybe, some documentation.

**Comment by RustyYato** [comment]
@ckaran don't worry about it, finishing up your Ph.D is more important than this crate!

@kw-fn Yes, as @ckaran mentioned this crate is still active, I'm currently a little busy during the day, so it may take me a bit to respond, but I will respond if you want guidance.

**Pull request closed without merging**
