### PR TITLE
Extract from `TypeSet` to a new crate `typsy`

### PR DESCRIPTION
**Pull request by RustyYato**
`TypeList` which is more general and can handle an arbitrary number of projections, it should be possible to bolt on tuples again for ergonomics.

### CODE REVIEW

**Comment by ckaran** [comment]
Sorry, my mistake!  I thought clicking on the button would let me look at the changes, not approve it! :scream:

**Comment by RustyYato** [comment]
[`typsy`](https://github.com/RustyYato/typsy) is a new crate I built which is heavily influenced by [`frunk`](https://github.com/lloydmeta/frunk). I still need to work on it a bit more. I don't like having to wrap every `Map`/`Fold`/`Any` call in a `Simple` or `Baked`, but I do need the type parameter on `Baked` to implement ad-hoc callables (which are not used in `gfp`).

**Comment by RustyYato** [comment]
This should be done, but I still need to do a final check to make sure I haven't introduced or removed any behaviors unintentionally.

**Comment by RustyYato** [comment]
Ok, I think this is finally good to go

**Pull request merged**
