### PR TITLE
Improve docs

### LINKED ISSUE #20: Feature request: Improve documentation & examples
I've been keeping an eye on this project since you started it, but my rust-fu is not good enough to be able to read the macros and know what I need to do.  Could you improve the documentation, and provide examples of how to use this project?  At some point I'd like to start writing an intrusive collections crate, and this will be the core of that work.

### PR DESCRIPTION
**Pull request by RustyYato**
Fixes #20

### CODE REVIEW

**Comment by ckaran** [comment]
@RustyYato ping! 

I'm still following this project, and I noticed that you never merged this back in.  Maybe you should? :wink:

**Comment by RustyYato** [comment]
Oh man, it's been ages since I looked at this crar3

**Comment by ckaran** [comment]
Thank you!  I know the feeling, I had a mental list of things I wanted to do with this crate, but now I only remember that I was planning on using it for intrusive collections...

**Review by ckaran — COMMENTED** [review]
I can't tell if you've set me up as a reviewer for this PR or not, but every time I click on my notifications, it dumps me at the review page...

**Comment by RustyYato** [comment]
Oh, it looks like I have set you up as a reviewer, that was unintentional. As far as I know, I can't remove a review request, but since you left a review it shouldn't bug you again. Sorry about that.

**Comment by ckaran** [comment]
Not a problem, I'm flattered! :grin: I just didn't want you to be blocked on me.

**Comment by RustyYato** [comment]
@ckaran  I got the fmt check fixed, it turns out that when you added the rustfmt.toml, `report_todo = "Never"` was in there, and that caused the fmt check to fail, also there was a problem with the action setup that meant that rustfmt wasn't actually installed, so I fixed both of those. Now CI should be green if things are good.

**Review by ckaran — COMMENTED** [review]
Do you need me to approve the changes for you to continue?  If so, I'll just approve whatever you put in.

**Comment by RustyYato** [comment]
No, I can push things through without a review, thanks for offering

**Review by ckaran — COMMENTED** [review]
:+1:

**Pull request merged**
